<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ml</string>
		<string>sml</string>
		<string>cm</string>
		<string>sig</string>
	</array>
	<key>name</key>
	<string>SML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.sml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.sml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.sml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.sml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match regular function like: fun myFunc (args) =</string>
			<key>match</key>
			<string>\b(fun|and)\s+([a-zA-Z_'$][\w']*)(\(|\s+)(.+?)(\))?\s*(=)</string>
			<key>name</key>
			<string>meta.function.sml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.sml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.sml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.sml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.sml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match anonymous function like: fn (args) =&gt;</string>
			<key>match</key>
			<string>\b(fn)\s+(\()?(.*?)(\))?\s*(=&gt;)</string>
			<key>name</key>
			<string>meta.function.sml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SML keywords</string>
			<key>match</key>
			<string>\b(open|if|functor|then|local|else|andalso|orelse|true|false|and|raise|handle|structure|struct|signature|sig|fun|let|val|in|end|case|print|of|fn|type|datatype|option|int|unit|word|real|char|string|substring|exn|array|vector|ref|bool|NONE|SOME|nil|list|LESS|EQUAL|GREATER|exception|as|abstype|do|infix|infixr|nonfix|op|rec|with|withtype|while|eqtype|include|sharing|not)\b</string>
			<key>name</key>
			<string>keyword.source.sml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword operators</string>
			<key>match</key>
			<string>(\+|\-|\*|\/|\bdiv\b|\bmod\b|\||!|:\=|\=|\^|&gt;\=|&lt;\=|&lt;&gt;|&gt;|&lt;|~|:)</string>
			<key>name</key>
			<string>keyword.operator.sml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric constants</string>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.sml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built in types</string>
			<key>match</key>
			<string>\b[A-Z]([A-z0-9]*)\b</string>
			<key>name</key>
			<string>support.type.sml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built in functions</string>
			<key>match</key>
			<string>\b(o|@)\b</string>
			<key>name</key>
			<string>support.function.sml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String constant</string>
			<key>match</key>
			<string>"(\\"|[^"])*"</string>
			<key>name</key>
			<string>string.sml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>comment</key>
			<string>Comment</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.sml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Character</string>
			<key>match</key>
			<string>(\(\)|=&gt;|::|\[\]|-&gt;|:&gt;)</string>
			<key>name</key>
			<string>constant.character.sml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sml</string>
	<key>uuid</key>
	<string>c75fce86-de5e-40f0-b42e-1504c17b784a</string>
</dict>
</plist>
